classDiagram
   direction RL
   class AuditEvent { <<resource>>  }
   style AuditEvent fill:#7CB9E8
   class Practitioner { <<resource>> }
   style Practitioner fill:#7CB9E8   
   class PractitionerRole { <<resource>> }
   style PractitionerRole fill:#7CB9E8      
   class Organization { <<resource>> }
   style Organization fill:#7CB9E8         
   class Location { <<resource>> }
   style Location fill:#7CB9E8        
   class Patient { <<resource>> }
   style Patient fill:#7CB9E8           
   class Encounter { <<resource>> }
   style Encounter fill:#7CB9E8 
  
 
   class no_basis_Patient["no-basis-Patient"]  {<<profile>>}
   class no_basis_Location["no-basis-Location"] {<<profile>>}
   class no_basis_PractitionerRole["no-basis-PractitionerRole"] {<<profile>>}
   class no_basis_Organization["no-basis-Organization"] {<<profile>>}
   class no_basis_Practitioner["no-basis-Practitioner"] {<<profile>>}
   style no_basis_Practitioner fill:#33FF55 
   style no_basis_Patient fill:#33FF55 
   style no_basis_Location fill:#33FF55 
   style no_basis_Organization fill:#33FF55     
   style no_basis_PractitionerRole fill:#33FF55     
               
   class no-basis-auditevent {
     <<profile>>
     care-relation.purpose-of-use
     care-relation.purpose-of-use-details
     care-relation.decision-ref     
     toa
   }
  

   class auditevent-practitionerrole  {<<profile>>}
   class auditevent-department { 
     <<profile>>
     practitioner.department
   }   
  

   class auditevent-practitioner  {
     <<profile>>
     practitioner.identifier
     practitioner.hpr-nr
     practitioner.authorization
   }

   class auditevent-practitioner-legalentity {
     <<profile>>
     practitioner.legal-entity
   }
   class auditevent-practitioner-pointofcare {<<profile>>}
   class auditevent-practitioner-pointofcare-organization {
     <<profile>>
     practitioner.point-of-care
   }
   class auditevent-encounter {
     <<profile>>
     care-relation.healthcare-service
   }
   class auditevent-patient {
     <<profile>>
     patient.identifier
   }

   class auditevent-encounter-pointofcare {<<profile>>}
   class auditevent-encounter-pointofcare-organization {
     <<profile>>
     patient.point-of-care     
   }
   class auditevent-encounter-serviceprovider-organization {
     <<profile>>
     patient.department
   }

   AuditEvent <|-- no-basis-auditevent 
   no_basis_PractitionerRole <|-- auditevent-practitionerrole 
   no_basis_Practitioner <|-- auditevent-practitioner
   no_basis_Organization <|-- auditevent-department   
   no_basis_Organization <|-- auditevent-practitioner-legalentity
   no_basis_Organization <|-- auditevent-encounter-pointofcare-organization
   no_basis_Organization <|-- auditevent-practitioner-pointofcare-organization
   no_basis_Organization <|-- auditevent-encounter-serviceprovider-organization
   no_basis_Location <|-- auditevent-encounter-pointofcare
   no_basis_Location <|-- auditevent-practitioner-pointofcare
   Location <|-- no_basis_Location
   no_basis_Patient <|-- auditevent-patient
   Patient <|-- no_basis_Patient
   Encounter <|-- auditevent-encounter
   PractitionerRole <|-- no_basis_PractitionerRole
   Organization <|-- no_basis_Organization
   Practitioner <|--  no_basis_Practitioner
  
    auditevent-practitioner-pointofcare-organization *-- auditevent-practitioner-pointofcare : managingOrganization
    auditevent-practitioner-legalentity *-- auditevent-department : partOf
    auditevent-encounter-pointofcare *-- auditevent-encounter : location.location
    auditevent-encounter-serviceprovider-organization *-- auditevent-encounter: serviceProvider
    auditevent-encounter-pointofcare-organization *-- auditevent-encounter-pointofcare : managingOrganization
    auditevent-practitioner-pointofcare *-- auditevent-practitionerrole  : location
    auditevent-department *-- auditevent-practitionerrole  : organization
    auditevent-practitioner-legalentity *-- auditevent-practitionerrole  : organization
    auditevent-practitioner *-- auditevent-practitionerrole  : practitioner
    auditevent-patient *-- no-basis-auditevent  : _patient
    auditevent-encounter *-- no-basis-auditevent  : _encounter
    auditevent-practitionerrole  *-- no-basis-auditevent  : agent.who
    
    link AuditEvent "https://hl7.org/fhir/R4/auditevent.html" 
    link Practitioner "https://hl7.org/fhir/R4/practitioner.html" 
    link PractitionerRole "https://hl7.org/fhir/R4/practitionerrole.html" 
    link Organization "https://hl7.org/fhir/R4/organization.html" 
    link Location "https://hl7.org/fhir/R4/location.html" 
    link Patient  "https://hl7.org/fhir/R4/patient.html" 
    link Encounter "https://hl7.org/fhir/R4/encounter.html" 

    link no-basis-auditevent "StructureDefinition-no-basis-auditevent.html"
    link auditevent-practitionerrole  "StructureDefinition-auditevent-practitionerrole.html"
    link auditevent-department "StructureDefinition-auditevent-department.html"
    link auditevent-practitioner "StructureDefinition-auditevent-practitioner.html"
    link auditevent-practitioner-legalentity "StructureDefinition-auditevent-practitioner-legalentity.html"
    link auditevent-practitioner-pointofcare "StructureDefinition-auditevent-practitioner-pointofcare.html"
    link auditevent-practitioner-pointofcare-organization "StructureDefinition-auditevent-practitioner-pointofcare-organization.html"
    link auditevent-encounter "StructureDefinition-auditevent-encounter.html"
    link auditevent-patient "StructureDefinition-auditevent-patient.html"
    link auditevent-encounter-pointofcare "StructureDefinition-auditevent-encounter-pointofcare.html"
    link auditevent-encounter-pointofcare-organization "StructureDefinition-auditevent-encounter-pointofcare-organization.html"
    link auditevent-encounter-serviceprovider-organization "StructureDefinition-auditevent-encounter-serviceprovider-organization.html"
    link no_basis_Patient "https://simplifier.net/hl7norwayno-basis/nobasispatient"
    link no_basis_Location "https://simplifier.net/hl7norwayno-basis/nobasislocation"
    link no_basis_PractitionerRole "https://simplifier.net/hl7norwayno-basis/nobasispractitionerrole"
    link no_basis_Organization "https://simplifier.net/hl7norwayno-basis/nobasisorganization"
    link no_basis_Practitioner "https://simplifier.net/hl7norwayno-basis/nobasispractitioner"