classDiagram
   direction RL
   class AuditEvent { <<resource>>  }
   style AuditEvent fill:#7CB9E8
   class Practitioner { <<resource>> }
   style Practitioner fill:#7CB9E8   
   class PractitionerRole { <<resource>> }
   style PractitionerRole fill:#7CB9E8      
   class Organization { <<resource>> }
   style Organization fill:#7CB9E8         
   class Location { <<resource>> }
   style Location fill:#7CB9E8        
   class Patient { <<resource>> }
   style Patient fill:#7CB9E8           
   class Encounter { <<resource>> }
   style Encounter fill:#7CB9E8 
 
   class no_basis_Patient["no-basis-Patient"]  {<<profile>>}
   class no_basis_Location["no-basis-Location"] {<<profile>>}
   class no_basis_PractitionerRole["no-basis-PractitionerRole"] {<<profile>>}
   class no_basis_Organization["no-basis-Organization"] {<<profile>>}
   class no_basis_Practitioner["no-basis-Practitioner"] {<<profile>>}
   style no_basis_Practitioner fill:#33FF55 
   style no_basis_Patient fill:#33FF55 
   style no_basis_Location fill:#33FF55 
   style no_basis_Organization fill:#33FF55     
   style no_basis_PractitionerRole fill:#33FF55     
               
   class no-basis-auditevent {
     <<profile>>
     care-relation.purpose-of-use
     care-relation.purpose-of-use-details
     care-relation.decision-ref     
   }

   class no-basis-auditevent-practitionerrole  {<<profile>>}
   class no-basis-auditevent-department { 
     <<profile>>
     practitioner.department
   }   

   class no-basis-auditevent-practitioner  {
     <<profile>>
     practitioner.identifier
     practitioner.hpr-nr
     practitioner.authorization
   }

   class no-basis-auditevent-practitioner-legalentity {
     <<profile>>
     practitioner.legal-entity
   }
   class no-basis-auditevent-practitioner-pointofcare {<<profile>>}
   class no-basis-auditevent-practitioner-pointofcare-organization {
     <<profile>>
     practitioner.point-of-care
   }
   class no-basis-encounter-auditevent {
     <<profile>>
     care-relation.healthcare-service
   }
   class no-basis-patient-auditevent {
     <<profile>>
     patient.identifier
   }

   class no-basis-auditevent-encounter-pointofcare {<<profile>>}
   class no-basis-auditevent-encounter-pointofcare-organization {
     <<profile>>
     patient.point-of-care     
   }
   class no-basis-auditevent-encounter-serviceprovider-organization {
     <<profile>>
     patient.department
   }


   AuditEvent <|-- no-basis-auditevent 
   no_basis_PractitionerRole <|-- no-basis-auditevent-practitionerrole 
   no_basis_Practitioner <|-- no-basis-auditevent-practitioner
   no_basis_Organization <|-- no-basis-auditevent-department   
   no_basis_Organization <|-- no-basis-auditevent-practitioner-legalentity
   no_basis_Organization <|-- no-basis-auditevent-encounter-pointofcare-organization
   no_basis_Organization <|-- no-basis-auditevent-practitioner-pointofcare-organization
   no_basis_Organization <|-- no-basis-auditevent-encounter-serviceprovider-organization
   no_basis_Location <|-- no-basis-auditevent-encounter-pointofcare
   no_basis_Location <|-- no-basis-auditevent-practitioner-pointofcare
   Location <|-- no_basis_Location
   no_basis_Patient <|-- no-basis-patient-auditevent
   Patient <|-- no_basis_Patient
   Encounter <|-- no-basis-encounter-auditevent
   PractitionerRole <|-- no_basis_PractitionerRole
   Organization <|-- no_basis_Organization
   Practitioner <|--  no_basis_Practitioner
  
   
  
    no-basis-auditevent-practitioner-pointofcare-organization *-- no-basis-auditevent-practitioner-pointofcare : managingOrganization
    no-basis-auditevent-practitioner-legalentity *-- no-basis-auditevent-department : partOf
    no-basis-auditevent-encounter-pointofcare *-- no-basis-encounter-auditevent : location.location
    no-basis-auditevent-encounter-serviceprovider-organization *-- no-basis-encounter-auditevent: serviceProvider
    no-basis-auditevent-encounter-pointofcare-organization *-- no-basis-auditevent-encounter-pointofcare : managingOrganization
    no-basis-auditevent-practitioner-pointofcare *-- no-basis-auditevent-practitionerrole  : location
    no-basis-auditevent-department *-- no-basis-auditevent-practitionerrole  : organization
    no-basis-auditevent-practitioner-legalentity *-- no-basis-auditevent-practitionerrole  : organization
    no-basis-auditevent-practitioner *-- no-basis-auditevent-practitionerrole  : practitioner
    no-basis-patient-auditevent *-- no-basis-auditevent  : _patient
    no-basis-encounter-auditevent *-- no-basis-auditevent  : _encounter
    no-basis-auditevent-practitionerrole  *-- no-basis-auditevent  : agent.who
    

    link AuditEvent "https://hl7.org/fhir/R4/auditevent.html" 
    link Practitioner "https://hl7.org/fhir/R4/practitioner.html" 
    link PractitionerRole "https://hl7.org/fhir/R4/practitionerrole.html" 
    link Organization "https://hl7.org/fhir/R4/organization.html" 
    link Location "https://hl7.org/fhir/R4/location.html" 
    link Patient  "https://hl7.org/fhir/R4/patient.html" 
    link Encounter "https://hl7.org/fhir/R4/encounter.html" 

    link no-basis-auditevent "StructureDefinition-no-basis-auditevent.html"
    link no-basis-auditevent-practitionerrole  "StructureDefinition-AuditEventNorwayPractitionerRole.html"
    link no-basis-auditevent-department "StructureDefinition-AuditEventNorwayPractitionerDepartment.html"
    link no-basis-auditevent-practitioner "StructureDefinition-AuditEventNorwayPractitioner.html"
    link no-basis-auditevent-practitioner-legalentity "StructureDefinition-AuditEventNorwayPractitionerLegalEntity.html"
    link no-basis-auditevent-practitioner-pointofcare "StructureDefinition-AuditEventNorwayPractitionerPointOfCare.html"
    link no-basis-auditevent-practitioner-pointofcare-organization "StructureDefinition-AuditEventNorwayPractitionerPointOfCareOrganization.html"
    link no-basis-encounter-auditevent "StructureDefinition-no-basis-encounter-auditevent.html"
    link no-basis-patient-auditevent "StructureDefinition-no-basis-patient-auditevent.html"
    link no-basis-auditevent-encounter-pointofcare "StructureDefinition-AuditEventNorwayEncounterPointOfCare.html"
    link no-basis-auditevent-encounter-pointofcare-organization "StructureDefinition-AuditEventNorwayEncounterPointOfCareOrganization.html"
    link no-basis-auditevent-encounter-serviceprovider-organization "StructureDefinition-AuditEventNorwayEncounterServiceProviderOrganization.html"
    link no_basis_Patient "https://simplifier.net/hl7norwayno-basis/nobasispatient"
    link no_basis_Location "https://simplifier.net/hl7norwayno-basis/nobasislocation"
    link no_basis_PractitionerRole "https://simplifier.net/hl7norwayno-basis/nobasispractitionerrole"
    link no_basis_Organization "https://simplifier.net/hl7norwayno-basis/nobasisorganization"
    link no_basis_Practitioner "https://simplifier.net/hl7norwayno-basis/nobasispractitioner"

  
  
  


