name: AuditEvent-gh-pages-no-basis-snapshots

on:
  workflow_dispatch:

env:
  IG: igs/AuditEvent

# The following jobs are equal for all IGs and can be moved to a common composite-action if 'uses'-support is added, see:
# https://github.com/actions/runner/blob/main/docs/adrs/1144-composite-actions.md
jobs:
  publish:
    runs-on: ubuntu-latest
    container: hl7fhir/ig-publisher-base:latest 
    steps:
      - uses: actions/checkout@v3    
      - name: Install hl7.fhir.no.basis-2.2.0-snapshots and build
        run: |
          echo "NPM install fhir r4 core 4.0.1 from package registry"
          npm --registry https://packages.simplifier.net install hl7.fhir.r4.core@4.0.1
          echo "NPM install fhir no-basis220 from local tgz"
          npm install igs/snapshots/hl7.fhir.no.basis-2.2.0-snapshots.tgz
          # echo "List node_modules directory"
          # ls -al ./node_modules     
          # echo "List node_modules hl7.fhir.no.basis directory"
          # ls -al ./node_modules/hl7.fhir.no.basis         
          echo "Make home publisher .fhir packages no-basis"
          # mkdir -p /home/publisher/.fhir/packages/hl7.fhir.no.basis#2.2.0/package
          mkdir -p /github/home/.fhir/packages/hl7.fhir.no.basis#2.2.0/package
          # ls -al /home/publisher/.fhir/packages/hl7.fhir.no.basis#2.2.0/package
          echo "Copy no-basis to /home/publisher/.fhir/packages/hl7.fhir.no.basis#2.2.0/package"
          # cp -r ./node_modules/hl7.fhir.no.basis/* /home/publisher/.fhir/packages/hl7.fhir.no.basis#2.2.0/package
          cp -r ./node_modules/hl7.fhir.no.basis/* /github/home/.fhir/packages/hl7.fhir.no.basis#2.2.0/package 
          # ls -al /home/publisher/.fhir/packages/hl7.fhir.no.basis#2.2.0/package
          cd ${{ env.IG }}
          echo "get latest publisher"
          curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar --create-dirs
          #pwd
          #ls -lag
          #node --version
          #npm --version
          npm install -g fsh-sushi
          # sushi help
          echo "Run publisher: java -jar publisher.jar publisher -ig ./${{ env.IG }}/ig.ini"
          java -jar ./input-cache/publisher.jar publisher -ig ig.ini

